# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/definitions/server_messages.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/definitions/server_messages.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\'proto/definitions/server_messages.proto\"\x97\x01\n\x14MessageToServerProto\x12\x11\n\tclient_id\x18\x01 \x01(\x05\x12\x1f\n\x04type\x18\x02 \x01(\x0e\x32\x11.MessageTypeProto\x12\r\n\x05value\x18\x03 \x01(\x05\x12\"\n\tdirection\x18\x04 \x01(\x0e\x32\x0f.DirectionProto\x12\x18\n\x10message_accepted\x18\x05 \x01(\x08\"~\n\x0bLizardProto\x12\n\n\x02\x63h\x18\x01 \x01(\x05\x12\t\n\x01x\x18\x02 \x01(\x05\x12\t\n\x01y\x18\x03 \x01(\x05\x12\r\n\x05score\x18\x04 \x01(\x05\x12+\n\x12previous_direction\x18\x05 \x01(\x0e\x32\x0f.DirectionProto\x12\x11\n\tis_winner\x18\x06 \x01(\x08\"S\n\nRoachProto\x12\n\n\x02\x63h\x18\x01 \x01(\x05\x12\t\n\x01x\x18\x02 \x01(\x05\x12\t\n\x01y\x18\x03 \x01(\x05\x12\x10\n\x08is_eaten\x18\x04 \x01(\x08\x12\x11\n\ttimestamp\x18\x05 \x01(\x03\"-\n\tWaspProto\x12\n\n\x02\x63h\x18\x01 \x01(\x05\x12\t\n\x01x\x18\x02 \x01(\x05\x12\t\n\x01y\x18\x03 \x01(\x05*7\n\x0e\x44irectionProto\x12\x06\n\x02UP\x10\x00\x12\x08\n\x04\x44OWN\x10\x01\x12\x08\n\x04LEFT\x10\x02\x12\t\n\x05RIGHT\x10\x03*=\n\x10MessageTypeProto\x12\x0b\n\x07\x43ONNECT\x10\x00\x12\x0c\n\x08MOVEMENT\x10\x01\x12\x0e\n\nDISCONNECT\x10\x02*T\n\x0f\x43lientTypeProto\x12\n\n\x06LIZARD\x10\x00\x12\t\n\x05ROACH\x10\x01\x12\x08\n\x04WASP\x10\x02\x12\x0f\n\x0b\x44ISPLAY_APP\x10\x03\x12\x0f\n\x0bLIZARD_BODY\x10\x04\x62\x06proto3'
)

_DIRECTIONPROTO = _descriptor.EnumDescriptor(
  name='DirectionProto',
  full_name='DirectionProto',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UP', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DOWN', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LEFT', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RIGHT', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=457,
  serialized_end=512,
)
_sym_db.RegisterEnumDescriptor(_DIRECTIONPROTO)

DirectionProto = enum_type_wrapper.EnumTypeWrapper(_DIRECTIONPROTO)
_MESSAGETYPEPROTO = _descriptor.EnumDescriptor(
  name='MessageTypeProto',
  full_name='MessageTypeProto',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CONNECT', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MOVEMENT', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DISCONNECT', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=514,
  serialized_end=575,
)
_sym_db.RegisterEnumDescriptor(_MESSAGETYPEPROTO)

MessageTypeProto = enum_type_wrapper.EnumTypeWrapper(_MESSAGETYPEPROTO)
_CLIENTTYPEPROTO = _descriptor.EnumDescriptor(
  name='ClientTypeProto',
  full_name='ClientTypeProto',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LIZARD', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ROACH', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='WASP', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DISPLAY_APP', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LIZARD_BODY', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=577,
  serialized_end=661,
)
_sym_db.RegisterEnumDescriptor(_CLIENTTYPEPROTO)

ClientTypeProto = enum_type_wrapper.EnumTypeWrapper(_CLIENTTYPEPROTO)
UP = 0
DOWN = 1
LEFT = 2
RIGHT = 3
CONNECT = 0
MOVEMENT = 1
DISCONNECT = 2
LIZARD = 0
ROACH = 1
WASP = 2
DISPLAY_APP = 3
LIZARD_BODY = 4



_MESSAGETOSERVERPROTO = _descriptor.Descriptor(
  name='MessageToServerProto',
  full_name='MessageToServerProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='client_id', full_name='MessageToServerProto.client_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='MessageToServerProto.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='MessageToServerProto.value', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='direction', full_name='MessageToServerProto.direction', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message_accepted', full_name='MessageToServerProto.message_accepted', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=195,
)


_LIZARDPROTO = _descriptor.Descriptor(
  name='LizardProto',
  full_name='LizardProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ch', full_name='LizardProto.ch', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='x', full_name='LizardProto.x', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='LizardProto.y', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='score', full_name='LizardProto.score', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='previous_direction', full_name='LizardProto.previous_direction', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_winner', full_name='LizardProto.is_winner', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=197,
  serialized_end=323,
)


_ROACHPROTO = _descriptor.Descriptor(
  name='RoachProto',
  full_name='RoachProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ch', full_name='RoachProto.ch', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='x', full_name='RoachProto.x', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='RoachProto.y', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_eaten', full_name='RoachProto.is_eaten', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='RoachProto.timestamp', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=325,
  serialized_end=408,
)


_WASPPROTO = _descriptor.Descriptor(
  name='WaspProto',
  full_name='WaspProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ch', full_name='WaspProto.ch', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='x', full_name='WaspProto.x', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='WaspProto.y', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=410,
  serialized_end=455,
)

_MESSAGETOSERVERPROTO.fields_by_name['type'].enum_type = _MESSAGETYPEPROTO
_MESSAGETOSERVERPROTO.fields_by_name['direction'].enum_type = _DIRECTIONPROTO
_LIZARDPROTO.fields_by_name['previous_direction'].enum_type = _DIRECTIONPROTO
DESCRIPTOR.message_types_by_name['MessageToServerProto'] = _MESSAGETOSERVERPROTO
DESCRIPTOR.message_types_by_name['LizardProto'] = _LIZARDPROTO
DESCRIPTOR.message_types_by_name['RoachProto'] = _ROACHPROTO
DESCRIPTOR.message_types_by_name['WaspProto'] = _WASPPROTO
DESCRIPTOR.enum_types_by_name['DirectionProto'] = _DIRECTIONPROTO
DESCRIPTOR.enum_types_by_name['MessageTypeProto'] = _MESSAGETYPEPROTO
DESCRIPTOR.enum_types_by_name['ClientTypeProto'] = _CLIENTTYPEPROTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MessageToServerProto = _reflection.GeneratedProtocolMessageType('MessageToServerProto', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGETOSERVERPROTO,
  '__module__' : 'proto.definitions.server_messages_pb2'
  # @@protoc_insertion_point(class_scope:MessageToServerProto)
  })
_sym_db.RegisterMessage(MessageToServerProto)

LizardProto = _reflection.GeneratedProtocolMessageType('LizardProto', (_message.Message,), {
  'DESCRIPTOR' : _LIZARDPROTO,
  '__module__' : 'proto.definitions.server_messages_pb2'
  # @@protoc_insertion_point(class_scope:LizardProto)
  })
_sym_db.RegisterMessage(LizardProto)

RoachProto = _reflection.GeneratedProtocolMessageType('RoachProto', (_message.Message,), {
  'DESCRIPTOR' : _ROACHPROTO,
  '__module__' : 'proto.definitions.server_messages_pb2'
  # @@protoc_insertion_point(class_scope:RoachProto)
  })
_sym_db.RegisterMessage(RoachProto)

WaspProto = _reflection.GeneratedProtocolMessageType('WaspProto', (_message.Message,), {
  'DESCRIPTOR' : _WASPPROTO,
  '__module__' : 'proto.definitions.server_messages_pb2'
  # @@protoc_insertion_point(class_scope:WaspProto)
  })
_sym_db.RegisterMessage(WaspProto)


# @@protoc_insertion_point(module_scope)
