# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/definitions/window_data.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/definitions/window_data.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n#proto/definitions/window_data.proto\"J\n\x0eLayerCharProto\x12\n\n\x02\x63h\x18\x01 \x01(\x05\x12\x11\n\tclient_id\x18\x02 \x01(\x05\x12\x19\n\x11position_in_array\x18\x03 \x01(\x05\"O\n\x0eLayerCellProto\x12\x1e\n\x05stack\x18\x01 \x03(\x0b\x32\x0f.LayerCharProto\x12\x0b\n\x03top\x18\x02 \x01(\x05\x12\x10\n\x08\x63\x61pacity\x18\x03 \x01(\x05\"R\n\x11WindowMatrixProto\x12\x1e\n\x05\x63\x65lls\x18\x01 \x03(\x0b\x32\x0f.LayerCellProto\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\"5\n\x0fWindowDataProto\x12\"\n\x06matrix\x18\x01 \x01(\x0b\x32\x12.WindowMatrixProto\".\n\x11ScoresUpdateProto\x12\r\n\x05score\x18\x01 \x01(\x05\x12\n\n\x02\x63h\x18\x02 \x01(\x05\"\xb3\x01\n\x10\x46ieldUpdateProto\x12&\n\rupdated_cells\x18\x01 \x03(\x0b\x32\x0f.LayerCellProto\x12\x1c\n\x14updated_cell_indexes\x18\x02 \x03(\x05\x12\"\n\x06scores\x18\x03 \x03(\x0b\x32\x12.ScoresUpdateProto\x12\x1d\n\x15size_of_updated_cells\x18\x04 \x01(\x05\x12\x16\n\x0esize_of_scores\x18\x05 \x01(\x05\x62\x06proto3'
)




_LAYERCHARPROTO = _descriptor.Descriptor(
  name='LayerCharProto',
  full_name='LayerCharProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ch', full_name='LayerCharProto.ch', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='client_id', full_name='LayerCharProto.client_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='position_in_array', full_name='LayerCharProto.position_in_array', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=113,
)


_LAYERCELLPROTO = _descriptor.Descriptor(
  name='LayerCellProto',
  full_name='LayerCellProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='stack', full_name='LayerCellProto.stack', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='top', full_name='LayerCellProto.top', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='capacity', full_name='LayerCellProto.capacity', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=115,
  serialized_end=194,
)


_WINDOWMATRIXPROTO = _descriptor.Descriptor(
  name='WindowMatrixProto',
  full_name='WindowMatrixProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cells', full_name='WindowMatrixProto.cells', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='width', full_name='WindowMatrixProto.width', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='height', full_name='WindowMatrixProto.height', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=196,
  serialized_end=278,
)


_WINDOWDATAPROTO = _descriptor.Descriptor(
  name='WindowDataProto',
  full_name='WindowDataProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='matrix', full_name='WindowDataProto.matrix', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=280,
  serialized_end=333,
)


_SCORESUPDATEPROTO = _descriptor.Descriptor(
  name='ScoresUpdateProto',
  full_name='ScoresUpdateProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='score', full_name='ScoresUpdateProto.score', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ch', full_name='ScoresUpdateProto.ch', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=335,
  serialized_end=381,
)


_FIELDUPDATEPROTO = _descriptor.Descriptor(
  name='FieldUpdateProto',
  full_name='FieldUpdateProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='updated_cells', full_name='FieldUpdateProto.updated_cells', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='updated_cell_indexes', full_name='FieldUpdateProto.updated_cell_indexes', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='scores', full_name='FieldUpdateProto.scores', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='size_of_updated_cells', full_name='FieldUpdateProto.size_of_updated_cells', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='size_of_scores', full_name='FieldUpdateProto.size_of_scores', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=384,
  serialized_end=563,
)

_LAYERCELLPROTO.fields_by_name['stack'].message_type = _LAYERCHARPROTO
_WINDOWMATRIXPROTO.fields_by_name['cells'].message_type = _LAYERCELLPROTO
_WINDOWDATAPROTO.fields_by_name['matrix'].message_type = _WINDOWMATRIXPROTO
_FIELDUPDATEPROTO.fields_by_name['updated_cells'].message_type = _LAYERCELLPROTO
_FIELDUPDATEPROTO.fields_by_name['scores'].message_type = _SCORESUPDATEPROTO
DESCRIPTOR.message_types_by_name['LayerCharProto'] = _LAYERCHARPROTO
DESCRIPTOR.message_types_by_name['LayerCellProto'] = _LAYERCELLPROTO
DESCRIPTOR.message_types_by_name['WindowMatrixProto'] = _WINDOWMATRIXPROTO
DESCRIPTOR.message_types_by_name['WindowDataProto'] = _WINDOWDATAPROTO
DESCRIPTOR.message_types_by_name['ScoresUpdateProto'] = _SCORESUPDATEPROTO
DESCRIPTOR.message_types_by_name['FieldUpdateProto'] = _FIELDUPDATEPROTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LayerCharProto = _reflection.GeneratedProtocolMessageType('LayerCharProto', (_message.Message,), {
  'DESCRIPTOR' : _LAYERCHARPROTO,
  '__module__' : 'proto.definitions.window_data_pb2'
  # @@protoc_insertion_point(class_scope:LayerCharProto)
  })
_sym_db.RegisterMessage(LayerCharProto)

LayerCellProto = _reflection.GeneratedProtocolMessageType('LayerCellProto', (_message.Message,), {
  'DESCRIPTOR' : _LAYERCELLPROTO,
  '__module__' : 'proto.definitions.window_data_pb2'
  # @@protoc_insertion_point(class_scope:LayerCellProto)
  })
_sym_db.RegisterMessage(LayerCellProto)

WindowMatrixProto = _reflection.GeneratedProtocolMessageType('WindowMatrixProto', (_message.Message,), {
  'DESCRIPTOR' : _WINDOWMATRIXPROTO,
  '__module__' : 'proto.definitions.window_data_pb2'
  # @@protoc_insertion_point(class_scope:WindowMatrixProto)
  })
_sym_db.RegisterMessage(WindowMatrixProto)

WindowDataProto = _reflection.GeneratedProtocolMessageType('WindowDataProto', (_message.Message,), {
  'DESCRIPTOR' : _WINDOWDATAPROTO,
  '__module__' : 'proto.definitions.window_data_pb2'
  # @@protoc_insertion_point(class_scope:WindowDataProto)
  })
_sym_db.RegisterMessage(WindowDataProto)

ScoresUpdateProto = _reflection.GeneratedProtocolMessageType('ScoresUpdateProto', (_message.Message,), {
  'DESCRIPTOR' : _SCORESUPDATEPROTO,
  '__module__' : 'proto.definitions.window_data_pb2'
  # @@protoc_insertion_point(class_scope:ScoresUpdateProto)
  })
_sym_db.RegisterMessage(ScoresUpdateProto)

FieldUpdateProto = _reflection.GeneratedProtocolMessageType('FieldUpdateProto', (_message.Message,), {
  'DESCRIPTOR' : _FIELDUPDATEPROTO,
  '__module__' : 'proto.definitions.window_data_pb2'
  # @@protoc_insertion_point(class_scope:FieldUpdateProto)
  })
_sym_db.RegisterMessage(FieldUpdateProto)


# @@protoc_insertion_point(module_scope)
