/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: server_messages.proto */

#ifndef PROTOBUF_C_server_5fmessages_2eproto__INCLUDED
#define PROTOBUF_C_server_5fmessages_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _MessageToServerProto MessageToServerProto;
typedef struct _LizardProto LizardProto;
typedef struct _RoachProto RoachProto;
typedef struct _WaspProto WaspProto;


/* --- enums --- */

typedef enum _DirectionProto {
  DIRECTION_PROTO__UP = 0,
  DIRECTION_PROTO__DOWN = 1,
  DIRECTION_PROTO__LEFT = 2,
  DIRECTION_PROTO__RIGHT = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(DIRECTION_PROTO)
} DirectionProto;
typedef enum _MessageTypeProto {
  MESSAGE_TYPE_PROTO__CONNECT = 0,
  MESSAGE_TYPE_PROTO__MOVEMENT = 1,
  MESSAGE_TYPE_PROTO__DISCONNECT = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(MESSAGE_TYPE_PROTO)
} MessageTypeProto;
typedef enum _ClientTypeProto {
  CLIENT_TYPE_PROTO__LIZARD = 0,
  CLIENT_TYPE_PROTO__ROACH = 1,
  CLIENT_TYPE_PROTO__WASP = 2,
  CLIENT_TYPE_PROTO__DISPLAY_APP = 3,
  CLIENT_TYPE_PROTO__LIZARD_BODY = 4
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(CLIENT_TYPE_PROTO)
} ClientTypeProto;

/* --- messages --- */

/*
 * Message structure
 */
struct  _MessageToServerProto
{
  ProtobufCMessage base;
  /*
   * 1 = lizard, 2 = roach, 3 = display-app
   */
  int32_t client_id;
  /*
   * 1 = connect, 2 = movement
   */
  MessageTypeProto type;
  /*
   * usage depends on client_id and type
   */
  int32_t value;
  /*
   * direction to move the roach
   */
  DirectionProto direction;
  /*
   * true = message accepted, false = message rejected
   */
  protobuf_c_boolean message_accepted;
};
#define MESSAGE_TO_SERVER_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&message_to_server_proto__descriptor) \
    , 0, MESSAGE_TYPE_PROTO__CONNECT, 0, DIRECTION_PROTO__UP, 0 }


/*
 * New structures
 */
struct  _LizardProto
{
  ProtobufCMessage base;
  int32_t ch;
  int32_t x;
  int32_t y;
  int32_t score;
  DirectionProto previous_direction;
  /*
   * True if winner, False otherwise
   */
  protobuf_c_boolean is_winner;
};
#define LIZARD_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&lizard_proto__descriptor) \
    , 0, 0, 0, 0, DIRECTION_PROTO__UP, 0 }


struct  _RoachProto
{
  ProtobufCMessage base;
  int32_t ch;
  int32_t x;
  int32_t y;
  protobuf_c_boolean is_eaten;
  int64_t timestamp;
};
#define ROACH_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&roach_proto__descriptor) \
    , 0, 0, 0, 0, 0 }


struct  _WaspProto
{
  ProtobufCMessage base;
  int32_t ch;
  int32_t x;
  int32_t y;
};
#define WASP_PROTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&wasp_proto__descriptor) \
    , 0, 0, 0 }


/* MessageToServerProto methods */
void   message_to_server_proto__init
                     (MessageToServerProto         *message);
size_t message_to_server_proto__get_packed_size
                     (const MessageToServerProto   *message);
size_t message_to_server_proto__pack
                     (const MessageToServerProto   *message,
                      uint8_t             *out);
size_t message_to_server_proto__pack_to_buffer
                     (const MessageToServerProto   *message,
                      ProtobufCBuffer     *buffer);
MessageToServerProto *
       message_to_server_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   message_to_server_proto__free_unpacked
                     (MessageToServerProto *message,
                      ProtobufCAllocator *allocator);
/* LizardProto methods */
void   lizard_proto__init
                     (LizardProto         *message);
size_t lizard_proto__get_packed_size
                     (const LizardProto   *message);
size_t lizard_proto__pack
                     (const LizardProto   *message,
                      uint8_t             *out);
size_t lizard_proto__pack_to_buffer
                     (const LizardProto   *message,
                      ProtobufCBuffer     *buffer);
LizardProto *
       lizard_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   lizard_proto__free_unpacked
                     (LizardProto *message,
                      ProtobufCAllocator *allocator);
/* RoachProto methods */
void   roach_proto__init
                     (RoachProto         *message);
size_t roach_proto__get_packed_size
                     (const RoachProto   *message);
size_t roach_proto__pack
                     (const RoachProto   *message,
                      uint8_t             *out);
size_t roach_proto__pack_to_buffer
                     (const RoachProto   *message,
                      ProtobufCBuffer     *buffer);
RoachProto *
       roach_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   roach_proto__free_unpacked
                     (RoachProto *message,
                      ProtobufCAllocator *allocator);
/* WaspProto methods */
void   wasp_proto__init
                     (WaspProto         *message);
size_t wasp_proto__get_packed_size
                     (const WaspProto   *message);
size_t wasp_proto__pack
                     (const WaspProto   *message,
                      uint8_t             *out);
size_t wasp_proto__pack_to_buffer
                     (const WaspProto   *message,
                      ProtobufCBuffer     *buffer);
WaspProto *
       wasp_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   wasp_proto__free_unpacked
                     (WaspProto *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*MessageToServerProto_Closure)
                 (const MessageToServerProto *message,
                  void *closure_data);
typedef void (*LizardProto_Closure)
                 (const LizardProto *message,
                  void *closure_data);
typedef void (*RoachProto_Closure)
                 (const RoachProto *message,
                  void *closure_data);
typedef void (*WaspProto_Closure)
                 (const WaspProto *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    direction_proto__descriptor;
extern const ProtobufCEnumDescriptor    message_type_proto__descriptor;
extern const ProtobufCEnumDescriptor    client_type_proto__descriptor;
extern const ProtobufCMessageDescriptor message_to_server_proto__descriptor;
extern const ProtobufCMessageDescriptor lizard_proto__descriptor;
extern const ProtobufCMessageDescriptor roach_proto__descriptor;
extern const ProtobufCMessageDescriptor wasp_proto__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_server_5fmessages_2eproto__INCLUDED */
