/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: server_messages.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "server_messages.pb-c.h"
void   message_to_server__init
                     (MessageToServer         *message)
{
  static const MessageToServer init_value = MESSAGE_TO_SERVER__INIT;
  *message = init_value;
}
size_t message_to_server__get_packed_size
                     (const MessageToServer *message)
{
  assert(message->base.descriptor == &message_to_server__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t message_to_server__pack
                     (const MessageToServer *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &message_to_server__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t message_to_server__pack_to_buffer
                     (const MessageToServer *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &message_to_server__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MessageToServer *
       message_to_server__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MessageToServer *)
     protobuf_c_message_unpack (&message_to_server__descriptor,
                                allocator, len, data);
}
void   message_to_server__free_unpacked
                     (MessageToServer *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &message_to_server__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   lizard__init
                     (Lizard         *message)
{
  static const Lizard init_value = LIZARD__INIT;
  *message = init_value;
}
size_t lizard__get_packed_size
                     (const Lizard *message)
{
  assert(message->base.descriptor == &lizard__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t lizard__pack
                     (const Lizard *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &lizard__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t lizard__pack_to_buffer
                     (const Lizard *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &lizard__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Lizard *
       lizard__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Lizard *)
     protobuf_c_message_unpack (&lizard__descriptor,
                                allocator, len, data);
}
void   lizard__free_unpacked
                     (Lizard *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &lizard__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   roach__init
                     (Roach         *message)
{
  static const Roach init_value = ROACH__INIT;
  *message = init_value;
}
size_t roach__get_packed_size
                     (const Roach *message)
{
  assert(message->base.descriptor == &roach__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t roach__pack
                     (const Roach *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &roach__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t roach__pack_to_buffer
                     (const Roach *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &roach__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Roach *
       roach__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Roach *)
     protobuf_c_message_unpack (&roach__descriptor,
                                allocator, len, data);
}
void   roach__free_unpacked
                     (Roach *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &roach__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   wasp__init
                     (Wasp         *message)
{
  static const Wasp init_value = WASP__INIT;
  *message = init_value;
}
size_t wasp__get_packed_size
                     (const Wasp *message)
{
  assert(message->base.descriptor == &wasp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t wasp__pack
                     (const Wasp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &wasp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t wasp__pack_to_buffer
                     (const Wasp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &wasp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Wasp *
       wasp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Wasp *)
     protobuf_c_message_unpack (&wasp__descriptor,
                                allocator, len, data);
}
void   wasp__free_unpacked
                     (Wasp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &wasp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   field_update_movement__init
                     (FieldUpdateMovement         *message)
{
  static const FieldUpdateMovement init_value = FIELD_UPDATE_MOVEMENT__INIT;
  *message = init_value;
}
size_t field_update_movement__get_packed_size
                     (const FieldUpdateMovement *message)
{
  assert(message->base.descriptor == &field_update_movement__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t field_update_movement__pack
                     (const FieldUpdateMovement *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &field_update_movement__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t field_update_movement__pack_to_buffer
                     (const FieldUpdateMovement *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &field_update_movement__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
FieldUpdateMovement *
       field_update_movement__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (FieldUpdateMovement *)
     protobuf_c_message_unpack (&field_update_movement__descriptor,
                                allocator, len, data);
}
void   field_update_movement__free_unpacked
                     (FieldUpdateMovement *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &field_update_movement__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   field_update_connect__init
                     (FieldUpdateConnect         *message)
{
  static const FieldUpdateConnect init_value = FIELD_UPDATE_CONNECT__INIT;
  *message = init_value;
}
size_t field_update_connect__get_packed_size
                     (const FieldUpdateConnect *message)
{
  assert(message->base.descriptor == &field_update_connect__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t field_update_connect__pack
                     (const FieldUpdateConnect *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &field_update_connect__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t field_update_connect__pack_to_buffer
                     (const FieldUpdateConnect *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &field_update_connect__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
FieldUpdateConnect *
       field_update_connect__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (FieldUpdateConnect *)
     protobuf_c_message_unpack (&field_update_connect__descriptor,
                                allocator, len, data);
}
void   field_update_connect__free_unpacked
                     (FieldUpdateConnect *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &field_update_connect__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   field_update_disconnect__init
                     (FieldUpdateDisconnect         *message)
{
  static const FieldUpdateDisconnect init_value = FIELD_UPDATE_DISCONNECT__INIT;
  *message = init_value;
}
size_t field_update_disconnect__get_packed_size
                     (const FieldUpdateDisconnect *message)
{
  assert(message->base.descriptor == &field_update_disconnect__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t field_update_disconnect__pack
                     (const FieldUpdateDisconnect *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &field_update_disconnect__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t field_update_disconnect__pack_to_buffer
                     (const FieldUpdateDisconnect *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &field_update_disconnect__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
FieldUpdateDisconnect *
       field_update_disconnect__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (FieldUpdateDisconnect *)
     protobuf_c_message_unpack (&field_update_disconnect__descriptor,
                                allocator, len, data);
}
void   field_update_disconnect__free_unpacked
                     (FieldUpdateDisconnect *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &field_update_disconnect__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   roach_mover_message__init
                     (RoachMoverMessage         *message)
{
  static const RoachMoverMessage init_value = ROACH_MOVER_MESSAGE__INIT;
  *message = init_value;
}
size_t roach_mover_message__get_packed_size
                     (const RoachMoverMessage *message)
{
  assert(message->base.descriptor == &roach_mover_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t roach_mover_message__pack
                     (const RoachMoverMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &roach_mover_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t roach_mover_message__pack_to_buffer
                     (const RoachMoverMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &roach_mover_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RoachMoverMessage *
       roach_mover_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RoachMoverMessage *)
     protobuf_c_message_unpack (&roach_mover_message__descriptor,
                                allocator, len, data);
}
void   roach_mover_message__free_unpacked
                     (RoachMoverMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &roach_mover_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   lizard_mover_message__init
                     (LizardMoverMessage         *message)
{
  static const LizardMoverMessage init_value = LIZARD_MOVER_MESSAGE__INIT;
  *message = init_value;
}
size_t lizard_mover_message__get_packed_size
                     (const LizardMoverMessage *message)
{
  assert(message->base.descriptor == &lizard_mover_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t lizard_mover_message__pack
                     (const LizardMoverMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &lizard_mover_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t lizard_mover_message__pack_to_buffer
                     (const LizardMoverMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &lizard_mover_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
LizardMoverMessage *
       lizard_mover_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (LizardMoverMessage *)
     protobuf_c_message_unpack (&lizard_mover_message__descriptor,
                                allocator, len, data);
}
void   lizard_mover_message__free_unpacked
                     (LizardMoverMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &lizard_mover_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   wasp_mover_message__init
                     (WaspMoverMessage         *message)
{
  static const WaspMoverMessage init_value = WASP_MOVER_MESSAGE__INIT;
  *message = init_value;
}
size_t wasp_mover_message__get_packed_size
                     (const WaspMoverMessage *message)
{
  assert(message->base.descriptor == &wasp_mover_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t wasp_mover_message__pack
                     (const WaspMoverMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &wasp_mover_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t wasp_mover_message__pack_to_buffer
                     (const WaspMoverMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &wasp_mover_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
WaspMoverMessage *
       wasp_mover_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (WaspMoverMessage *)
     protobuf_c_message_unpack (&wasp_mover_message__descriptor,
                                allocator, len, data);
}
void   wasp_mover_message__free_unpacked
                     (WaspMoverMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &wasp_mover_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor message_to_server__field_descriptors[5] =
{
  {
    "client_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(MessageToServer, client_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(MessageToServer, type),
    &message_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(MessageToServer, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "direction",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(MessageToServer, direction),
    &direction__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "message_accepted",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(MessageToServer, message_accepted),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned message_to_server__field_indices_by_name[] = {
  0,   /* field[0] = client_id */
  3,   /* field[3] = direction */
  4,   /* field[4] = message_accepted */
  1,   /* field[1] = type */
  2,   /* field[2] = value */
};
static const ProtobufCIntRange message_to_server__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor message_to_server__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "MessageToServer",
  "MessageToServer",
  "MessageToServer",
  "",
  sizeof(MessageToServer),
  5,
  message_to_server__field_descriptors,
  message_to_server__field_indices_by_name,
  1,  message_to_server__number_ranges,
  (ProtobufCMessageInit) message_to_server__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor lizard__field_descriptors[6] =
{
  {
    "ch",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Lizard, ch),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "x",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Lizard, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Lizard, y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "score",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Lizard, score),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "previous_direction",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Lizard, previous_direction),
    &direction__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "is_winner",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Lizard, is_winner),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned lizard__field_indices_by_name[] = {
  0,   /* field[0] = ch */
  5,   /* field[5] = is_winner */
  4,   /* field[4] = previous_direction */
  3,   /* field[3] = score */
  1,   /* field[1] = x */
  2,   /* field[2] = y */
};
static const ProtobufCIntRange lizard__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor lizard__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Lizard",
  "Lizard",
  "Lizard",
  "",
  sizeof(Lizard),
  6,
  lizard__field_descriptors,
  lizard__field_indices_by_name,
  1,  lizard__number_ranges,
  (ProtobufCMessageInit) lizard__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor roach__field_descriptors[5] =
{
  {
    "ch",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Roach, ch),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "x",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Roach, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Roach, y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "is_eaten",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Roach, is_eaten),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timestamp",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Roach, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned roach__field_indices_by_name[] = {
  0,   /* field[0] = ch */
  3,   /* field[3] = is_eaten */
  4,   /* field[4] = timestamp */
  1,   /* field[1] = x */
  2,   /* field[2] = y */
};
static const ProtobufCIntRange roach__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor roach__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Roach",
  "Roach",
  "Roach",
  "",
  sizeof(Roach),
  5,
  roach__field_descriptors,
  roach__field_indices_by_name,
  1,  roach__number_ranges,
  (ProtobufCMessageInit) roach__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor wasp__field_descriptors[3] =
{
  {
    "ch",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Wasp, ch),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "x",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Wasp, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Wasp, y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned wasp__field_indices_by_name[] = {
  0,   /* field[0] = ch */
  1,   /* field[1] = x */
  2,   /* field[2] = y */
};
static const ProtobufCIntRange wasp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor wasp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Wasp",
  "Wasp",
  "Wasp",
  "",
  sizeof(Wasp),
  3,
  wasp__field_descriptors,
  wasp__field_indices_by_name,
  1,  wasp__number_ranges,
  (ProtobufCMessageInit) wasp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor field_update_movement__field_descriptors[7] =
{
  {
    "num_roaches",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(FieldUpdateMovement, num_roaches),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "num_lizards",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(FieldUpdateMovement, num_lizards),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "message",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(FieldUpdateMovement, message),
    &message_to_server__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "new_x",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(FieldUpdateMovement, new_x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "new_y",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(FieldUpdateMovement, new_y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "prev_direction",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(FieldUpdateMovement, prev_direction),
    &direction__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "is_eaten",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(FieldUpdateMovement, is_eaten),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned field_update_movement__field_indices_by_name[] = {
  6,   /* field[6] = is_eaten */
  2,   /* field[2] = message */
  3,   /* field[3] = new_x */
  4,   /* field[4] = new_y */
  1,   /* field[1] = num_lizards */
  0,   /* field[0] = num_roaches */
  5,   /* field[5] = prev_direction */
};
static const ProtobufCIntRange field_update_movement__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor field_update_movement__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "FieldUpdateMovement",
  "FieldUpdateMovement",
  "FieldUpdateMovement",
  "",
  sizeof(FieldUpdateMovement),
  7,
  field_update_movement__field_descriptors,
  field_update_movement__field_indices_by_name,
  1,  field_update_movement__number_ranges,
  (ProtobufCMessageInit) field_update_movement__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor field_update_connect__field_descriptors[5] =
{
  {
    "client_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(FieldUpdateConnect, client_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "position_in_array",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(FieldUpdateConnect, position_in_array),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "connected_lizard",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(FieldUpdateConnect, connected_lizard),
    &lizard__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "connected_roach",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(FieldUpdateConnect, connected_roach),
    &roach__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "message",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(FieldUpdateConnect, message),
    &message_to_server__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned field_update_connect__field_indices_by_name[] = {
  0,   /* field[0] = client_id */
  2,   /* field[2] = connected_lizard */
  3,   /* field[3] = connected_roach */
  4,   /* field[4] = message */
  1,   /* field[1] = position_in_array */
};
static const ProtobufCIntRange field_update_connect__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor field_update_connect__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "FieldUpdateConnect",
  "FieldUpdateConnect",
  "FieldUpdateConnect",
  "",
  sizeof(FieldUpdateConnect),
  5,
  field_update_connect__field_descriptors,
  field_update_connect__field_indices_by_name,
  1,  field_update_connect__number_ranges,
  (ProtobufCMessageInit) field_update_connect__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor field_update_disconnect__field_descriptors[3] =
{
  {
    "client_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(FieldUpdateDisconnect, client_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "position_in_array",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(FieldUpdateDisconnect, position_in_array),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "message",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(FieldUpdateDisconnect, message),
    &message_to_server__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned field_update_disconnect__field_indices_by_name[] = {
  0,   /* field[0] = client_id */
  2,   /* field[2] = message */
  1,   /* field[1] = position_in_array */
};
static const ProtobufCIntRange field_update_disconnect__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor field_update_disconnect__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "FieldUpdateDisconnect",
  "FieldUpdateDisconnect",
  "FieldUpdateDisconnect",
  "",
  sizeof(FieldUpdateDisconnect),
  3,
  field_update_disconnect__field_descriptors,
  field_update_disconnect__field_indices_by_name,
  1,  field_update_disconnect__number_ranges,
  (ProtobufCMessageInit) field_update_disconnect__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor roach_mover_message__field_descriptors[3] =
{
  {
    "roaches",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(RoachMoverMessage, n_roaches),
    offsetof(RoachMoverMessage, roaches),
    &roach__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "num_roaches",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(RoachMoverMessage, num_roaches),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "slot_roaches",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(RoachMoverMessage, slot_roaches),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned roach_mover_message__field_indices_by_name[] = {
  1,   /* field[1] = num_roaches */
  0,   /* field[0] = roaches */
  2,   /* field[2] = slot_roaches */
};
static const ProtobufCIntRange roach_mover_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor roach_mover_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RoachMoverMessage",
  "RoachMoverMessage",
  "RoachMoverMessage",
  "",
  sizeof(RoachMoverMessage),
  3,
  roach_mover_message__field_descriptors,
  roach_mover_message__field_indices_by_name,
  1,  roach_mover_message__number_ranges,
  (ProtobufCMessageInit) roach_mover_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor lizard_mover_message__field_descriptors[3] =
{
  {
    "lizards",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(LizardMoverMessage, n_lizards),
    offsetof(LizardMoverMessage, lizards),
    &lizard__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "num_lizards",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(LizardMoverMessage, num_lizards),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "slot_lizards",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(LizardMoverMessage, slot_lizards),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned lizard_mover_message__field_indices_by_name[] = {
  0,   /* field[0] = lizards */
  1,   /* field[1] = num_lizards */
  2,   /* field[2] = slot_lizards */
};
static const ProtobufCIntRange lizard_mover_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor lizard_mover_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "LizardMoverMessage",
  "LizardMoverMessage",
  "LizardMoverMessage",
  "",
  sizeof(LizardMoverMessage),
  3,
  lizard_mover_message__field_descriptors,
  lizard_mover_message__field_indices_by_name,
  1,  lizard_mover_message__number_ranges,
  (ProtobufCMessageInit) lizard_mover_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor wasp_mover_message__field_descriptors[3] =
{
  {
    "wasps",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(WaspMoverMessage, n_wasps),
    offsetof(WaspMoverMessage, wasps),
    &wasp__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "num_wasps",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(WaspMoverMessage, num_wasps),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "slot_wasps",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(WaspMoverMessage, slot_wasps),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned wasp_mover_message__field_indices_by_name[] = {
  1,   /* field[1] = num_wasps */
  2,   /* field[2] = slot_wasps */
  0,   /* field[0] = wasps */
};
static const ProtobufCIntRange wasp_mover_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor wasp_mover_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "WaspMoverMessage",
  "WaspMoverMessage",
  "WaspMoverMessage",
  "",
  sizeof(WaspMoverMessage),
  3,
  wasp_mover_message__field_descriptors,
  wasp_mover_message__field_indices_by_name,
  1,  wasp_mover_message__number_ranges,
  (ProtobufCMessageInit) wasp_mover_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue direction__enum_values_by_number[4] =
{
  { "UP", "DIRECTION__UP", 0 },
  { "DOWN", "DIRECTION__DOWN", 1 },
  { "LEFT", "DIRECTION__LEFT", 2 },
  { "RIGHT", "DIRECTION__RIGHT", 3 },
};
static const ProtobufCIntRange direction__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex direction__enum_values_by_name[4] =
{
  { "DOWN", 1 },
  { "LEFT", 2 },
  { "RIGHT", 3 },
  { "UP", 0 },
};
const ProtobufCEnumDescriptor direction__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Direction",
  "Direction",
  "Direction",
  "",
  4,
  direction__enum_values_by_number,
  4,
  direction__enum_values_by_name,
  1,
  direction__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue message_type__enum_values_by_number[3] =
{
  { "CONNECT", "MESSAGE_TYPE__CONNECT", 0 },
  { "MOVEMENT", "MESSAGE_TYPE__MOVEMENT", 1 },
  { "DISCONNECT", "MESSAGE_TYPE__DISCONNECT", 2 },
};
static const ProtobufCIntRange message_type__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex message_type__enum_values_by_name[3] =
{
  { "CONNECT", 0 },
  { "DISCONNECT", 2 },
  { "MOVEMENT", 1 },
};
const ProtobufCEnumDescriptor message_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "MessageType",
  "MessageType",
  "MessageType",
  "",
  3,
  message_type__enum_values_by_number,
  3,
  message_type__enum_values_by_name,
  1,
  message_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue client_type__enum_values_by_number[4] =
{
  { "LIZARD", "CLIENT_TYPE__LIZARD", 0 },
  { "ROACH", "CLIENT_TYPE__ROACH", 1 },
  { "DISPLAY_APP", "CLIENT_TYPE__DISPLAY_APP", 2 },
  { "LIZARD_BODY", "CLIENT_TYPE__LIZARD_BODY", 3 },
};
static const ProtobufCIntRange client_type__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex client_type__enum_values_by_name[4] =
{
  { "DISPLAY_APP", 2 },
  { "LIZARD", 0 },
  { "LIZARD_BODY", 3 },
  { "ROACH", 1 },
};
const ProtobufCEnumDescriptor client_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ClientType",
  "ClientType",
  "ClientType",
  "",
  4,
  client_type__enum_values_by_number,
  4,
  client_type__enum_values_by_name,
  1,
  client_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
