/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: server_messages.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "server_messages.pb-c.h"
void   message_to_server_proto__init
                     (MessageToServerProto         *message)
{
  static const MessageToServerProto init_value = MESSAGE_TO_SERVER_PROTO__INIT;
  *message = init_value;
}
size_t message_to_server_proto__get_packed_size
                     (const MessageToServerProto *message)
{
  assert(message->base.descriptor == &message_to_server_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t message_to_server_proto__pack
                     (const MessageToServerProto *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &message_to_server_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t message_to_server_proto__pack_to_buffer
                     (const MessageToServerProto *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &message_to_server_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MessageToServerProto *
       message_to_server_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MessageToServerProto *)
     protobuf_c_message_unpack (&message_to_server_proto__descriptor,
                                allocator, len, data);
}
void   message_to_server_proto__free_unpacked
                     (MessageToServerProto *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &message_to_server_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   lizard_proto__init
                     (LizardProto         *message)
{
  static const LizardProto init_value = LIZARD_PROTO__INIT;
  *message = init_value;
}
size_t lizard_proto__get_packed_size
                     (const LizardProto *message)
{
  assert(message->base.descriptor == &lizard_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t lizard_proto__pack
                     (const LizardProto *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &lizard_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t lizard_proto__pack_to_buffer
                     (const LizardProto *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &lizard_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
LizardProto *
       lizard_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (LizardProto *)
     protobuf_c_message_unpack (&lizard_proto__descriptor,
                                allocator, len, data);
}
void   lizard_proto__free_unpacked
                     (LizardProto *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &lizard_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   roach_proto__init
                     (RoachProto         *message)
{
  static const RoachProto init_value = ROACH_PROTO__INIT;
  *message = init_value;
}
size_t roach_proto__get_packed_size
                     (const RoachProto *message)
{
  assert(message->base.descriptor == &roach_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t roach_proto__pack
                     (const RoachProto *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &roach_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t roach_proto__pack_to_buffer
                     (const RoachProto *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &roach_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RoachProto *
       roach_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RoachProto *)
     protobuf_c_message_unpack (&roach_proto__descriptor,
                                allocator, len, data);
}
void   roach_proto__free_unpacked
                     (RoachProto *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &roach_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   wasp_proto__init
                     (WaspProto         *message)
{
  static const WaspProto init_value = WASP_PROTO__INIT;
  *message = init_value;
}
size_t wasp_proto__get_packed_size
                     (const WaspProto *message)
{
  assert(message->base.descriptor == &wasp_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t wasp_proto__pack
                     (const WaspProto *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &wasp_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t wasp_proto__pack_to_buffer
                     (const WaspProto *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &wasp_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
WaspProto *
       wasp_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (WaspProto *)
     protobuf_c_message_unpack (&wasp_proto__descriptor,
                                allocator, len, data);
}
void   wasp_proto__free_unpacked
                     (WaspProto *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &wasp_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   field_update_movement_proto__init
                     (FieldUpdateMovementProto         *message)
{
  static const FieldUpdateMovementProto init_value = FIELD_UPDATE_MOVEMENT_PROTO__INIT;
  *message = init_value;
}
size_t field_update_movement_proto__get_packed_size
                     (const FieldUpdateMovementProto *message)
{
  assert(message->base.descriptor == &field_update_movement_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t field_update_movement_proto__pack
                     (const FieldUpdateMovementProto *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &field_update_movement_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t field_update_movement_proto__pack_to_buffer
                     (const FieldUpdateMovementProto *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &field_update_movement_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
FieldUpdateMovementProto *
       field_update_movement_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (FieldUpdateMovementProto *)
     protobuf_c_message_unpack (&field_update_movement_proto__descriptor,
                                allocator, len, data);
}
void   field_update_movement_proto__free_unpacked
                     (FieldUpdateMovementProto *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &field_update_movement_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   field_update_connect_proto__init
                     (FieldUpdateConnectProto         *message)
{
  static const FieldUpdateConnectProto init_value = FIELD_UPDATE_CONNECT_PROTO__INIT;
  *message = init_value;
}
size_t field_update_connect_proto__get_packed_size
                     (const FieldUpdateConnectProto *message)
{
  assert(message->base.descriptor == &field_update_connect_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t field_update_connect_proto__pack
                     (const FieldUpdateConnectProto *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &field_update_connect_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t field_update_connect_proto__pack_to_buffer
                     (const FieldUpdateConnectProto *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &field_update_connect_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
FieldUpdateConnectProto *
       field_update_connect_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (FieldUpdateConnectProto *)
     protobuf_c_message_unpack (&field_update_connect_proto__descriptor,
                                allocator, len, data);
}
void   field_update_connect_proto__free_unpacked
                     (FieldUpdateConnectProto *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &field_update_connect_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   field_update_disconnect_proto__init
                     (FieldUpdateDisconnectProto         *message)
{
  static const FieldUpdateDisconnectProto init_value = FIELD_UPDATE_DISCONNECT_PROTO__INIT;
  *message = init_value;
}
size_t field_update_disconnect_proto__get_packed_size
                     (const FieldUpdateDisconnectProto *message)
{
  assert(message->base.descriptor == &field_update_disconnect_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t field_update_disconnect_proto__pack
                     (const FieldUpdateDisconnectProto *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &field_update_disconnect_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t field_update_disconnect_proto__pack_to_buffer
                     (const FieldUpdateDisconnectProto *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &field_update_disconnect_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
FieldUpdateDisconnectProto *
       field_update_disconnect_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (FieldUpdateDisconnectProto *)
     protobuf_c_message_unpack (&field_update_disconnect_proto__descriptor,
                                allocator, len, data);
}
void   field_update_disconnect_proto__free_unpacked
                     (FieldUpdateDisconnectProto *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &field_update_disconnect_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   roach_mover_message_proto__init
                     (RoachMoverMessageProto         *message)
{
  static const RoachMoverMessageProto init_value = ROACH_MOVER_MESSAGE_PROTO__INIT;
  *message = init_value;
}
size_t roach_mover_message_proto__get_packed_size
                     (const RoachMoverMessageProto *message)
{
  assert(message->base.descriptor == &roach_mover_message_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t roach_mover_message_proto__pack
                     (const RoachMoverMessageProto *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &roach_mover_message_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t roach_mover_message_proto__pack_to_buffer
                     (const RoachMoverMessageProto *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &roach_mover_message_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RoachMoverMessageProto *
       roach_mover_message_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RoachMoverMessageProto *)
     protobuf_c_message_unpack (&roach_mover_message_proto__descriptor,
                                allocator, len, data);
}
void   roach_mover_message_proto__free_unpacked
                     (RoachMoverMessageProto *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &roach_mover_message_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   lizard_mover_message_proto__init
                     (LizardMoverMessageProto         *message)
{
  static const LizardMoverMessageProto init_value = LIZARD_MOVER_MESSAGE_PROTO__INIT;
  *message = init_value;
}
size_t lizard_mover_message_proto__get_packed_size
                     (const LizardMoverMessageProto *message)
{
  assert(message->base.descriptor == &lizard_mover_message_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t lizard_mover_message_proto__pack
                     (const LizardMoverMessageProto *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &lizard_mover_message_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t lizard_mover_message_proto__pack_to_buffer
                     (const LizardMoverMessageProto *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &lizard_mover_message_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
LizardMoverMessageProto *
       lizard_mover_message_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (LizardMoverMessageProto *)
     protobuf_c_message_unpack (&lizard_mover_message_proto__descriptor,
                                allocator, len, data);
}
void   lizard_mover_message_proto__free_unpacked
                     (LizardMoverMessageProto *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &lizard_mover_message_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   wasp_mover_message_proto__init
                     (WaspMoverMessageProto         *message)
{
  static const WaspMoverMessageProto init_value = WASP_MOVER_MESSAGE_PROTO__INIT;
  *message = init_value;
}
size_t wasp_mover_message_proto__get_packed_size
                     (const WaspMoverMessageProto *message)
{
  assert(message->base.descriptor == &wasp_mover_message_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t wasp_mover_message_proto__pack
                     (const WaspMoverMessageProto *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &wasp_mover_message_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t wasp_mover_message_proto__pack_to_buffer
                     (const WaspMoverMessageProto *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &wasp_mover_message_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
WaspMoverMessageProto *
       wasp_mover_message_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (WaspMoverMessageProto *)
     protobuf_c_message_unpack (&wasp_mover_message_proto__descriptor,
                                allocator, len, data);
}
void   wasp_mover_message_proto__free_unpacked
                     (WaspMoverMessageProto *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &wasp_mover_message_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor message_to_server_proto__field_descriptors[5] =
{
  {
    "client_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(MessageToServerProto, client_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(MessageToServerProto, type),
    &message_type_proto__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(MessageToServerProto, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "direction",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(MessageToServerProto, direction),
    &direction_proto__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "message_accepted",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(MessageToServerProto, message_accepted),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned message_to_server_proto__field_indices_by_name[] = {
  0,   /* field[0] = client_id */
  3,   /* field[3] = direction */
  4,   /* field[4] = message_accepted */
  1,   /* field[1] = type */
  2,   /* field[2] = value */
};
static const ProtobufCIntRange message_to_server_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor message_to_server_proto__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "MessageToServerProto",
  "MessageToServerProto",
  "MessageToServerProto",
  "",
  sizeof(MessageToServerProto),
  5,
  message_to_server_proto__field_descriptors,
  message_to_server_proto__field_indices_by_name,
  1,  message_to_server_proto__number_ranges,
  (ProtobufCMessageInit) message_to_server_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor lizard_proto__field_descriptors[6] =
{
  {
    "ch",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(LizardProto, ch),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "x",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(LizardProto, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(LizardProto, y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "score",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(LizardProto, score),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "previous_direction",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(LizardProto, previous_direction),
    &direction_proto__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "is_winner",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(LizardProto, is_winner),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned lizard_proto__field_indices_by_name[] = {
  0,   /* field[0] = ch */
  5,   /* field[5] = is_winner */
  4,   /* field[4] = previous_direction */
  3,   /* field[3] = score */
  1,   /* field[1] = x */
  2,   /* field[2] = y */
};
static const ProtobufCIntRange lizard_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor lizard_proto__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "LizardProto",
  "LizardProto",
  "LizardProto",
  "",
  sizeof(LizardProto),
  6,
  lizard_proto__field_descriptors,
  lizard_proto__field_indices_by_name,
  1,  lizard_proto__number_ranges,
  (ProtobufCMessageInit) lizard_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor roach_proto__field_descriptors[5] =
{
  {
    "ch",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(RoachProto, ch),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "x",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(RoachProto, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(RoachProto, y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "is_eaten",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(RoachProto, is_eaten),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timestamp",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(RoachProto, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned roach_proto__field_indices_by_name[] = {
  0,   /* field[0] = ch */
  3,   /* field[3] = is_eaten */
  4,   /* field[4] = timestamp */
  1,   /* field[1] = x */
  2,   /* field[2] = y */
};
static const ProtobufCIntRange roach_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor roach_proto__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RoachProto",
  "RoachProto",
  "RoachProto",
  "",
  sizeof(RoachProto),
  5,
  roach_proto__field_descriptors,
  roach_proto__field_indices_by_name,
  1,  roach_proto__number_ranges,
  (ProtobufCMessageInit) roach_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor wasp_proto__field_descriptors[3] =
{
  {
    "ch",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(WaspProto, ch),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "x",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(WaspProto, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(WaspProto, y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned wasp_proto__field_indices_by_name[] = {
  0,   /* field[0] = ch */
  1,   /* field[1] = x */
  2,   /* field[2] = y */
};
static const ProtobufCIntRange wasp_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor wasp_proto__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "WaspProto",
  "WaspProto",
  "WaspProto",
  "",
  sizeof(WaspProto),
  3,
  wasp_proto__field_descriptors,
  wasp_proto__field_indices_by_name,
  1,  wasp_proto__number_ranges,
  (ProtobufCMessageInit) wasp_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor field_update_movement_proto__field_descriptors[7] =
{
  {
    "num_roaches",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(FieldUpdateMovementProto, num_roaches),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "num_lizards",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(FieldUpdateMovementProto, num_lizards),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "message",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(FieldUpdateMovementProto, message),
    &message_to_server_proto__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "new_x",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(FieldUpdateMovementProto, new_x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "new_y",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(FieldUpdateMovementProto, new_y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "prev_direction",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(FieldUpdateMovementProto, prev_direction),
    &direction_proto__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "is_eaten",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(FieldUpdateMovementProto, is_eaten),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned field_update_movement_proto__field_indices_by_name[] = {
  6,   /* field[6] = is_eaten */
  2,   /* field[2] = message */
  3,   /* field[3] = new_x */
  4,   /* field[4] = new_y */
  1,   /* field[1] = num_lizards */
  0,   /* field[0] = num_roaches */
  5,   /* field[5] = prev_direction */
};
static const ProtobufCIntRange field_update_movement_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor field_update_movement_proto__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "FieldUpdateMovementProto",
  "FieldUpdateMovementProto",
  "FieldUpdateMovementProto",
  "",
  sizeof(FieldUpdateMovementProto),
  7,
  field_update_movement_proto__field_descriptors,
  field_update_movement_proto__field_indices_by_name,
  1,  field_update_movement_proto__number_ranges,
  (ProtobufCMessageInit) field_update_movement_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor field_update_connect_proto__field_descriptors[5] =
{
  {
    "client_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(FieldUpdateConnectProto, client_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "position_in_array",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(FieldUpdateConnectProto, position_in_array),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "connected_lizard",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(FieldUpdateConnectProto, connected_lizard),
    &lizard_proto__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "connected_roach",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(FieldUpdateConnectProto, connected_roach),
    &roach_proto__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "message",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(FieldUpdateConnectProto, message),
    &message_to_server_proto__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned field_update_connect_proto__field_indices_by_name[] = {
  0,   /* field[0] = client_id */
  2,   /* field[2] = connected_lizard */
  3,   /* field[3] = connected_roach */
  4,   /* field[4] = message */
  1,   /* field[1] = position_in_array */
};
static const ProtobufCIntRange field_update_connect_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor field_update_connect_proto__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "FieldUpdateConnectProto",
  "FieldUpdateConnectProto",
  "FieldUpdateConnectProto",
  "",
  sizeof(FieldUpdateConnectProto),
  5,
  field_update_connect_proto__field_descriptors,
  field_update_connect_proto__field_indices_by_name,
  1,  field_update_connect_proto__number_ranges,
  (ProtobufCMessageInit) field_update_connect_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor field_update_disconnect_proto__field_descriptors[3] =
{
  {
    "client_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(FieldUpdateDisconnectProto, client_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "position_in_array",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(FieldUpdateDisconnectProto, position_in_array),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "message",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(FieldUpdateDisconnectProto, message),
    &message_to_server_proto__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned field_update_disconnect_proto__field_indices_by_name[] = {
  0,   /* field[0] = client_id */
  2,   /* field[2] = message */
  1,   /* field[1] = position_in_array */
};
static const ProtobufCIntRange field_update_disconnect_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor field_update_disconnect_proto__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "FieldUpdateDisconnectProto",
  "FieldUpdateDisconnectProto",
  "FieldUpdateDisconnectProto",
  "",
  sizeof(FieldUpdateDisconnectProto),
  3,
  field_update_disconnect_proto__field_descriptors,
  field_update_disconnect_proto__field_indices_by_name,
  1,  field_update_disconnect_proto__number_ranges,
  (ProtobufCMessageInit) field_update_disconnect_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor roach_mover_message_proto__field_descriptors[3] =
{
  {
    "roaches",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(RoachMoverMessageProto, n_roaches),
    offsetof(RoachMoverMessageProto, roaches),
    &roach_proto__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "num_roaches",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(RoachMoverMessageProto, num_roaches),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "slot_roaches",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(RoachMoverMessageProto, slot_roaches),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned roach_mover_message_proto__field_indices_by_name[] = {
  1,   /* field[1] = num_roaches */
  0,   /* field[0] = roaches */
  2,   /* field[2] = slot_roaches */
};
static const ProtobufCIntRange roach_mover_message_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor roach_mover_message_proto__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RoachMoverMessageProto",
  "RoachMoverMessageProto",
  "RoachMoverMessageProto",
  "",
  sizeof(RoachMoverMessageProto),
  3,
  roach_mover_message_proto__field_descriptors,
  roach_mover_message_proto__field_indices_by_name,
  1,  roach_mover_message_proto__number_ranges,
  (ProtobufCMessageInit) roach_mover_message_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor lizard_mover_message_proto__field_descriptors[3] =
{
  {
    "lizards",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(LizardMoverMessageProto, n_lizards),
    offsetof(LizardMoverMessageProto, lizards),
    &lizard_proto__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "num_lizards",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(LizardMoverMessageProto, num_lizards),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "slot_lizards",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(LizardMoverMessageProto, slot_lizards),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned lizard_mover_message_proto__field_indices_by_name[] = {
  0,   /* field[0] = lizards */
  1,   /* field[1] = num_lizards */
  2,   /* field[2] = slot_lizards */
};
static const ProtobufCIntRange lizard_mover_message_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor lizard_mover_message_proto__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "LizardMoverMessageProto",
  "LizardMoverMessageProto",
  "LizardMoverMessageProto",
  "",
  sizeof(LizardMoverMessageProto),
  3,
  lizard_mover_message_proto__field_descriptors,
  lizard_mover_message_proto__field_indices_by_name,
  1,  lizard_mover_message_proto__number_ranges,
  (ProtobufCMessageInit) lizard_mover_message_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor wasp_mover_message_proto__field_descriptors[3] =
{
  {
    "wasps",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(WaspMoverMessageProto, n_wasps),
    offsetof(WaspMoverMessageProto, wasps),
    &wasp_proto__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "num_wasps",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(WaspMoverMessageProto, num_wasps),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "slot_wasps",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(WaspMoverMessageProto, slot_wasps),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned wasp_mover_message_proto__field_indices_by_name[] = {
  1,   /* field[1] = num_wasps */
  2,   /* field[2] = slot_wasps */
  0,   /* field[0] = wasps */
};
static const ProtobufCIntRange wasp_mover_message_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor wasp_mover_message_proto__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "WaspMoverMessageProto",
  "WaspMoverMessageProto",
  "WaspMoverMessageProto",
  "",
  sizeof(WaspMoverMessageProto),
  3,
  wasp_mover_message_proto__field_descriptors,
  wasp_mover_message_proto__field_indices_by_name,
  1,  wasp_mover_message_proto__number_ranges,
  (ProtobufCMessageInit) wasp_mover_message_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue direction_proto__enum_values_by_number[4] =
{
  { "UP", "DIRECTION_PROTO__UP", 0 },
  { "DOWN", "DIRECTION_PROTO__DOWN", 1 },
  { "LEFT", "DIRECTION_PROTO__LEFT", 2 },
  { "RIGHT", "DIRECTION_PROTO__RIGHT", 3 },
};
static const ProtobufCIntRange direction_proto__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex direction_proto__enum_values_by_name[4] =
{
  { "DOWN", 1 },
  { "LEFT", 2 },
  { "RIGHT", 3 },
  { "UP", 0 },
};
const ProtobufCEnumDescriptor direction_proto__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "DirectionProto",
  "DirectionProto",
  "DirectionProto",
  "",
  4,
  direction_proto__enum_values_by_number,
  4,
  direction_proto__enum_values_by_name,
  1,
  direction_proto__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue message_type_proto__enum_values_by_number[3] =
{
  { "CONNECT", "MESSAGE_TYPE_PROTO__CONNECT", 0 },
  { "MOVEMENT", "MESSAGE_TYPE_PROTO__MOVEMENT", 1 },
  { "DISCONNECT", "MESSAGE_TYPE_PROTO__DISCONNECT", 2 },
};
static const ProtobufCIntRange message_type_proto__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex message_type_proto__enum_values_by_name[3] =
{
  { "CONNECT", 0 },
  { "DISCONNECT", 2 },
  { "MOVEMENT", 1 },
};
const ProtobufCEnumDescriptor message_type_proto__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "MessageTypeProto",
  "MessageTypeProto",
  "MessageTypeProto",
  "",
  3,
  message_type_proto__enum_values_by_number,
  3,
  message_type_proto__enum_values_by_name,
  1,
  message_type_proto__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue client_type_proto__enum_values_by_number[5] =
{
  { "LIZARD", "CLIENT_TYPE_PROTO__LIZARD", 0 },
  { "ROACH", "CLIENT_TYPE_PROTO__ROACH", 1 },
  { "WASP", "CLIENT_TYPE_PROTO__WASP", 2 },
  { "DISPLAY_APP", "CLIENT_TYPE_PROTO__DISPLAY_APP", 3 },
  { "LIZARD_BODY", "CLIENT_TYPE_PROTO__LIZARD_BODY", 4 },
};
static const ProtobufCIntRange client_type_proto__value_ranges[] = {
{0, 0},{0, 5}
};
static const ProtobufCEnumValueIndex client_type_proto__enum_values_by_name[5] =
{
  { "DISPLAY_APP", 3 },
  { "LIZARD", 0 },
  { "LIZARD_BODY", 4 },
  { "ROACH", 1 },
  { "WASP", 2 },
};
const ProtobufCEnumDescriptor client_type_proto__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ClientTypeProto",
  "ClientTypeProto",
  "ClientTypeProto",
  "",
  5,
  client_type_proto__enum_values_by_number,
  5,
  client_type_proto__enum_values_by_name,
  1,
  client_type_proto__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
