/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: window_data.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "window_data.pb-c.h"
void   layer_char__init
                     (LayerChar         *message)
{
  static const LayerChar init_value = LAYER_CHAR__INIT;
  *message = init_value;
}
size_t layer_char__get_packed_size
                     (const LayerChar *message)
{
  assert(message->base.descriptor == &layer_char__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t layer_char__pack
                     (const LayerChar *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &layer_char__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t layer_char__pack_to_buffer
                     (const LayerChar *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &layer_char__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
LayerChar *
       layer_char__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (LayerChar *)
     protobuf_c_message_unpack (&layer_char__descriptor,
                                allocator, len, data);
}
void   layer_char__free_unpacked
                     (LayerChar *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &layer_char__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   layer_cell__init
                     (LayerCell         *message)
{
  static const LayerCell init_value = LAYER_CELL__INIT;
  *message = init_value;
}
size_t layer_cell__get_packed_size
                     (const LayerCell *message)
{
  assert(message->base.descriptor == &layer_cell__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t layer_cell__pack
                     (const LayerCell *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &layer_cell__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t layer_cell__pack_to_buffer
                     (const LayerCell *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &layer_cell__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
LayerCell *
       layer_cell__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (LayerCell *)
     protobuf_c_message_unpack (&layer_cell__descriptor,
                                allocator, len, data);
}
void   layer_cell__free_unpacked
                     (LayerCell *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &layer_cell__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   window_matrix__init
                     (WindowMatrix         *message)
{
  static const WindowMatrix init_value = WINDOW_MATRIX__INIT;
  *message = init_value;
}
size_t window_matrix__get_packed_size
                     (const WindowMatrix *message)
{
  assert(message->base.descriptor == &window_matrix__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t window_matrix__pack
                     (const WindowMatrix *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &window_matrix__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t window_matrix__pack_to_buffer
                     (const WindowMatrix *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &window_matrix__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
WindowMatrix *
       window_matrix__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (WindowMatrix *)
     protobuf_c_message_unpack (&window_matrix__descriptor,
                                allocator, len, data);
}
void   window_matrix__free_unpacked
                     (WindowMatrix *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &window_matrix__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   window_data__init
                     (WindowData         *message)
{
  static const WindowData init_value = WINDOW_DATA__INIT;
  *message = init_value;
}
size_t window_data__get_packed_size
                     (const WindowData *message)
{
  assert(message->base.descriptor == &window_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t window_data__pack
                     (const WindowData *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &window_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t window_data__pack_to_buffer
                     (const WindowData *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &window_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
WindowData *
       window_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (WindowData *)
     protobuf_c_message_unpack (&window_data__descriptor,
                                allocator, len, data);
}
void   window_data__free_unpacked
                     (WindowData *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &window_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor layer_char__field_descriptors[3] =
{
  {
    "ch",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(LayerChar, ch),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "client_id",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(LayerChar, client_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "position_in_array",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(LayerChar, position_in_array),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned layer_char__field_indices_by_name[] = {
  0,   /* field[0] = ch */
  1,   /* field[1] = client_id */
  2,   /* field[2] = position_in_array */
};
static const ProtobufCIntRange layer_char__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor layer_char__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "LayerChar",
  "LayerChar",
  "LayerChar",
  "",
  sizeof(LayerChar),
  3,
  layer_char__field_descriptors,
  layer_char__field_indices_by_name,
  1,  layer_char__number_ranges,
  (ProtobufCMessageInit) layer_char__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor layer_cell__field_descriptors[3] =
{
  {
    "stack",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(LayerCell, n_stack),
    offsetof(LayerCell, stack),
    &layer_char__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "top",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(LayerCell, top),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "capacity",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(LayerCell, capacity),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned layer_cell__field_indices_by_name[] = {
  2,   /* field[2] = capacity */
  0,   /* field[0] = stack */
  1,   /* field[1] = top */
};
static const ProtobufCIntRange layer_cell__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor layer_cell__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "LayerCell",
  "LayerCell",
  "LayerCell",
  "",
  sizeof(LayerCell),
  3,
  layer_cell__field_descriptors,
  layer_cell__field_indices_by_name,
  1,  layer_cell__number_ranges,
  (ProtobufCMessageInit) layer_cell__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor window_matrix__field_descriptors[3] =
{
  {
    "cells",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(WindowMatrix, n_cells),
    offsetof(WindowMatrix, cells),
    &layer_cell__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "width",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(WindowMatrix, width),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "height",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(WindowMatrix, height),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned window_matrix__field_indices_by_name[] = {
  0,   /* field[0] = cells */
  2,   /* field[2] = height */
  1,   /* field[1] = width */
};
static const ProtobufCIntRange window_matrix__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor window_matrix__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "WindowMatrix",
  "WindowMatrix",
  "WindowMatrix",
  "",
  sizeof(WindowMatrix),
  3,
  window_matrix__field_descriptors,
  window_matrix__field_indices_by_name,
  1,  window_matrix__number_ranges,
  (ProtobufCMessageInit) window_matrix__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor window_data__field_descriptors[1] =
{
  {
    "matrix",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(WindowData, matrix),
    &window_matrix__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned window_data__field_indices_by_name[] = {
  0,   /* field[0] = matrix */
};
static const ProtobufCIntRange window_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor window_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "WindowData",
  "WindowData",
  "WindowData",
  "",
  sizeof(WindowData),
  1,
  window_data__field_descriptors,
  window_data__field_indices_by_name,
  1,  window_data__number_ranges,
  (ProtobufCMessageInit) window_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
